old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        promotions_queue:
            connection:            default
            exchange_options:      { name: 'promotions_queue', type: direct }
            queue_options:         { name: 'promotions_queue', routing_key: 'promotions_queue' }
            service_alias:         'producer.promotions.queue' # no alias by default
        new_queue:
            connection:         default
            exchange_options:   { name: 'new_queue', type: direct }
            queue_options:      { name: 'new_queue', routing_key: 'new_queue' }
            service_alias:      'producer.new.queue' # no alias by default


    consumers:
        promotions_queue:
            connection:       default
            exchange_options: { name: 'promotions_queue', type: direct }
            queue_options:    { name: 'promotions_queue', routing_key: 'promotions_queue' }
            callback:         App\Consumer\PromotionQueueConsumer
            enable_logger: true
            graceful_max_execution:
                timeout: 1800 # 30 minutes
                exit_code: 10 # default is 0
        new_queue:
            connection:       default
            exchange_options: { name: 'new_queue', type: direct }
            queue_options:    { name: 'new_queue', routing_key: 'new_queue' }
            callback:         App\Consumer\NewQueueConsumer
            enable_logger: true
            graceful_max_execution:
                timeout: 1800 # 30 minutes
                exit_code: 10 # default is 0